package com.ucfgroup.client.ucfpay;

import com.hframework.common.util.message.JsonUtils;
import org.junit.Test;
import com.ucfgroup.client.ucfpay.bean.*;

/**
 * generated by hframework on 2016-04-27.
 */
public class UcfpayClientTest   {

	@Test
	public void createOrder()  throws Exception{
			UcfPayResult result =UcfpayClient.createOrder("1000161","99",123,"511321198708084072","6226090107757003","张三丰","18610655490","网信理财红包","网信理财红包信息","fsdjkalfdjsafjdsal");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void confirmOrder()  throws Exception{
			UcfPayResult result =UcfpayClient.confirmOrder("100015","547775");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void resendSms()  throws Exception{
			UcfPayResult result =UcfpayClient.resendSms("1000161");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void queryCardBin()  throws Exception{
			UcfPayCardBinResult result =UcfpayClient.queryCardBin("6226090107757003");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void queryOrder()  throws Exception{
			UcfPayResult result =UcfpayClient.queryOrder("100014");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

  
 
}
