package com.ucfgroup.client.weixinpay;

import java.util.*;
import com.hframework.common.util.protocol.HttpClient;
import com.hframework.common.util.UrlHelper;
import java.text.MessageFormat;
import com.hframework.common.util.message.*;
import com.ucfgroup.client.weixinpay.bean.*;
import com.hframework.common.util.FileUtils;

/**
 * generated by hframework on 2016.
 */
public class WeixinpayClient   {

	
	public static UnifiedOrderResponse unifiedorder(UnifiedOrderRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getUnifiedorder());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/unifiedorder.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			UnifiedOrderResponse responseData = XmlUtils.readValue(result,UnifiedOrderResponse.class);
			return responseData.convert();
	}

	
	public static OrderQueryResponse orderquery(OrderQueryRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getOrderquery());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/orderquery.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			OrderQueryResponse responseData = XmlUtils.readValue(result,OrderQueryResponse.class);
			return responseData.convert();
	}

	
	public static CloseOrderResponse closeorder(CloseOrderRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getCloseorder());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/closeorder.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			CloseOrderResponse responseData = XmlUtils.readValue(result,CloseOrderResponse.class);
			return responseData.convert();
	}

	
	public static String downloadbill(DownloadBillRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getDownloadbill());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/downloadbill.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			return result;
	}

	
	public static RefundResponse refund(RefundRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getRefund());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/refund.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			RefundResponse responseData = XmlUtils.readValue(result,RefundResponse.class);
			return responseData.convert();
	}

	
	public static RefundQueryResponse refundquery(RefundQueryRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getRefundquery());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/refundquery.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			RefundQueryResponse responseData = XmlUtils.readValue(result,RefundQueryResponse.class);
			return responseData.convert();
	}

	
	public static WXPayNotifyResponse notice(WXPayNotifyRequest requestData)  throws Exception{
			Map<String, String> parameterMap = new LinkedHashMap();
			String url = UrlHelper.getUrlPath(WeixinpayConfig.getInstance().getNotice());
			String result;
			if("true".equals(WeixinpayConfig.getInstance().getTestModel())) {
			   result = FileUtils.readFile(Thread.currentThread().getContextClassLoader().getResource(
			          "third/weixinpay/notice.response").getPath());
			}else {
			   result = HttpClient.doXmlPost(url,requestData.convert());
			}
			WXPayNotifyResponse responseData = XmlUtils.readValue(result,WXPayNotifyResponse.class);
			return responseData.convert();
	}

  
 
}
