package com.hframework.reconciliation.bean;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.hframework.reconciliation.bean.config.*;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("config")
public class Config   {

	@XStreamAlias("global")
	private Global global;
	@XStreamAlias("services")
	private Services services;

    public Config() {
    }
   
 	 	 
     public Global getGlobal(){
     	return global;
     }

     public void setGlobal(Global global){
     	this.global = global;
     }
	 	 	 
     public Services getServices(){
     	return services;
     }

     public void setServices(Services services){
     	this.services = services;
     }
	 
}
