package com.ucfgroup.client.beetle.bean.getrepayplanresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class ListBean   {

	@JsonProperty("id")
	private String id;
	@JsonProperty("deal_name")
	private String dealName;
	@JsonProperty("repay_time")
	private String repayTime;
	@JsonProperty("real_repay_time")
	private String realRepayTime;
	@JsonProperty("repay_money")
	private String repayMoney;
	@JsonProperty("record_num")
	private String recordNum;
	@JsonProperty("deal_id")
	private String dealId;
	@JsonProperty("type")
	private String type;
	@JsonProperty("bt")
	private String bt;
	@JsonProperty("date")
	private String date;
	@JsonProperty("num")
	private String num;
	@JsonProperty("repay_date")
	private String repayDate;
	@JsonProperty("real_repay_date")
	private String realRepayDate;
	@XStreamOmitField
	private boolean converted;

    public ListBean() {
    }
 	
	public ListBean convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getDealName(){
     	return dealName;
     }

     public void setDealName(String dealName){
     	this.dealName = dealName;
     }
	 	 	 
     public String getRepayTime(){
     	return repayTime;
     }

     public void setRepayTime(String repayTime){
     	this.repayTime = repayTime;
     }
	 	 	 
     public String getRealRepayTime(){
     	return realRepayTime;
     }

     public void setRealRepayTime(String realRepayTime){
     	this.realRepayTime = realRepayTime;
     }
	 	 	 
     public String getRepayMoney(){
     	return repayMoney;
     }

     public void setRepayMoney(String repayMoney){
     	this.repayMoney = repayMoney;
     }
	 	 	 
     public String getRecordNum(){
     	return recordNum;
     }

     public void setRecordNum(String recordNum){
     	this.recordNum = recordNum;
     }
	 	 	 
     public String getDealId(){
     	return dealId;
     }

     public void setDealId(String dealId){
     	this.dealId = dealId;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getBt(){
     	return bt;
     }

     public void setBt(String bt){
     	this.bt = bt;
     }
	 	 	 
     public String getDate(){
     	return date;
     }

     public void setDate(String date){
     	this.date = date;
     }
	 	 	 
     public String getNum(){
     	return num;
     }

     public void setNum(String num){
     	this.num = num;
     }
	 	 	 
     public String getRepayDate(){
     	return repayDate;
     }

     public void setRepayDate(String repayDate){
     	this.repayDate = repayDate;
     }
	 	 	 
     public String getRealRepayDate(){
     	return realRepayDate;
     }

     public void setRealRepayDate(String realRepayDate){
     	this.realRepayDate = realRepayDate;
     }
	 	 
}
