package com.ucfgroup.client.weixinpay.bean;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
import com.hframework.common.util.message.*;
import com.ucfgroup.client.weixinpay.*;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("xml")
public class WXPayNotifyRequest   {

	@XStreamAlias("appid")
	private String appid;
	@XStreamAlias("attach")
	private String attach;
	@XStreamAlias("bank_type")
	private String bankType;
	@XStreamAlias("fee_type")
	private String feeType;
	@XStreamAlias("is_subscribe")
	private String isSubscribe;
	@XStreamAlias("mch_id")
	private String mchId;
	@XStreamAlias("nonce_str")
	private String nonceStr;
	@XStreamAlias("openid")
	private String openid;
	@XStreamAlias("out_trade_no")
	private String outTradeNo;
	@XStreamAlias("result_code")
	private String resultCode;
	@XStreamAlias("return_code")
	private String returnCode;
	@XStreamAlias("sign")
	private String sign;
	@XStreamAlias("sub_mch_id")
	private String subMchId;
	@XStreamAlias("time_end")
	private String timeEnd;
	@XStreamAlias("total_fee")
	private String totalFee;
	@XStreamAlias("trade_type")
	private String tradeType;
	@XStreamAlias("transaction_id")
	private String transactionId;
	@XStreamOmitField
	private boolean converted;

    public WXPayNotifyRequest() {
    }
 	
	public String getAppid() {
			return appid;
	}

	
	private void setAppid(String appid) {
			this.appid = appid;
	}

	
	public String getFeeType() {
			return feeType;
	}

	
	private void setFeeType(String feeType) {
			this.feeType = feeType;
	}

	
	public String getMchId() {
			return mchId;
	}

	
	private void setMchId(String mchId) {
			this.mchId = mchId;
	}

	
	public String getNonceStr() {
			return nonceStr;
	}

	
	private void setNonceStr(String nonceStr) {
			this.nonceStr = nonceStr;
	}

	
	public String getSign() {
			return sign;
	}

	
	private void setSign(String sign) {
			this.sign = sign;
	}

	
	public String getTradeType() {
			return tradeType;
	}

	
	private void setTradeType(String tradeType) {
			this.tradeType = tradeType;
	}

	
	public WXPayNotifyRequest convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   appid=WeixinpayConfig.getInstance().getAppid();
			   feeType=WeixinpayConfig.getInstance().getFeeType();
			   mchId=WeixinpayConfig.getInstance().getMchId();
			   nonceStr=WeixinpayHelper.md5RandomNumber();
			   sign=WeixinpayHelper.encryptSign(this);
			   tradeType=WeixinpayConfig.getInstance().getTradeType();
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 	 
     public String getAttach(){
     	return attach;
     }

     public void setAttach(String attach){
     	this.attach = attach;
     }
	 	 	 
     public String getBankType(){
     	return bankType;
     }

     public void setBankType(String bankType){
     	this.bankType = bankType;
     }
	 	 	 	 
     public String getIsSubscribe(){
     	return isSubscribe;
     }

     public void setIsSubscribe(String isSubscribe){
     	this.isSubscribe = isSubscribe;
     }
	 	 	 	 	 
     public String getOpenid(){
     	return openid;
     }

     public void setOpenid(String openid){
     	this.openid = openid;
     }
	 	 	 
     public String getOutTradeNo(){
     	return outTradeNo;
     }

     public void setOutTradeNo(String outTradeNo){
     	this.outTradeNo = outTradeNo;
     }
	 	 	 
     public String getResultCode(){
     	return resultCode;
     }

     public void setResultCode(String resultCode){
     	this.resultCode = resultCode;
     }
	 	 	 
     public String getReturnCode(){
     	return returnCode;
     }

     public void setReturnCode(String returnCode){
     	this.returnCode = returnCode;
     }
	 	 	 	 
     public String getSubMchId(){
     	return subMchId;
     }

     public void setSubMchId(String subMchId){
     	this.subMchId = subMchId;
     }
	 	 	 
     public String getTimeEnd(){
     	return timeEnd;
     }

     public void setTimeEnd(String timeEnd){
     	this.timeEnd = timeEnd;
     }
	 	 	 
     public String getTotalFee(){
     	return totalFee;
     }

     public void setTotalFee(String totalFee){
     	this.totalFee = totalFee;
     }
	 	 	 	 
     public String getTransactionId(){
     	return transactionId;
     }

     public void setTransactionId(String transactionId){
     	this.transactionId = transactionId;
     }
	 	 
}
