package com.ucfgroup.client.beetle.bean.getnodedataresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class GroupItem   {

	@JsonProperty("start_day")
	private String startDay;
	@JsonProperty("end_day")
	private String endDay;
	@JsonProperty("is_leaf")
	private String isLeaf;
	@JsonProperty("reg_num")
	private String regNum;
	@JsonProperty("invest_num")
	private String investNum;
	@JsonProperty("invest_count")
	private String investCount;
	@JsonProperty("curent_invest_num")
	private String curentInvestNum;
	@JsonProperty("firstinvest_num")
	private String firstinvestNum;
	@JsonProperty("invest_money")
	private String investMoney;
	@JsonProperty("invest_year_money")
	private String investYearMoney;
	@JsonProperty("ctime")
	private String ctime;
	@JsonProperty("user_status")
	private String userStatus;
	@JsonProperty("offer_date")
	private List<String> offerDateList;
	@JsonProperty("name")
	private String name;
	@JsonProperty("id")
	private String id;
	@JsonProperty("code")
	private String code;
	@JsonProperty("level")
	private String level;
	@JsonProperty("groupid")
	private String groupid;
	@JsonProperty("company")
	private String company;
	@JsonProperty("weight")
	private String weight;
	@JsonProperty("userb_num")
	private String userbNum;
	@XStreamOmitField
	private boolean converted;

    public GroupItem() {
    }
 	
	public GroupItem convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getStartDay(){
     	return startDay;
     }

     public void setStartDay(String startDay){
     	this.startDay = startDay;
     }
	 	 	 
     public String getEndDay(){
     	return endDay;
     }

     public void setEndDay(String endDay){
     	this.endDay = endDay;
     }
	 	 	 
     public String getIsLeaf(){
     	return isLeaf;
     }

     public void setIsLeaf(String isLeaf){
     	this.isLeaf = isLeaf;
     }
	 	 	 
     public String getRegNum(){
     	return regNum;
     }

     public void setRegNum(String regNum){
     	this.regNum = regNum;
     }
	 	 	 
     public String getInvestNum(){
     	return investNum;
     }

     public void setInvestNum(String investNum){
     	this.investNum = investNum;
     }
	 	 	 
     public String getInvestCount(){
     	return investCount;
     }

     public void setInvestCount(String investCount){
     	this.investCount = investCount;
     }
	 	 	 
     public String getCurentInvestNum(){
     	return curentInvestNum;
     }

     public void setCurentInvestNum(String curentInvestNum){
     	this.curentInvestNum = curentInvestNum;
     }
	 	 	 
     public String getFirstinvestNum(){
     	return firstinvestNum;
     }

     public void setFirstinvestNum(String firstinvestNum){
     	this.firstinvestNum = firstinvestNum;
     }
	 	 	 
     public String getInvestMoney(){
     	return investMoney;
     }

     public void setInvestMoney(String investMoney){
     	this.investMoney = investMoney;
     }
	 	 	 
     public String getInvestYearMoney(){
     	return investYearMoney;
     }

     public void setInvestYearMoney(String investYearMoney){
     	this.investYearMoney = investYearMoney;
     }
	 	 	 
     public String getCtime(){
     	return ctime;
     }

     public void setCtime(String ctime){
     	this.ctime = ctime;
     }
	 	 	 
     public String getUserStatus(){
     	return userStatus;
     }

     public void setUserStatus(String userStatus){
     	this.userStatus = userStatus;
     }
	 	 	 
     public List<String> getOfferDateList(){
     	return offerDateList;
     }

     public void setOfferDateList(List<String> offerDateList){
     	this.offerDateList = offerDateList;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }
	 	 	 
     public String getLevel(){
     	return level;
     }

     public void setLevel(String level){
     	this.level = level;
     }
	 	 	 
     public String getGroupid(){
     	return groupid;
     }

     public void setGroupid(String groupid){
     	this.groupid = groupid;
     }
	 	 	 
     public String getCompany(){
     	return company;
     }

     public void setCompany(String company){
     	this.company = company;
     }
	 	 	 
     public String getWeight(){
     	return weight;
     }

     public void setWeight(String weight){
     	this.weight = weight;
     }
	 	 	 
     public String getUserbNum(){
     	return userbNum;
     }

     public void setUserbNum(String userbNum){
     	this.userbNum = userbNum;
     }
	 	 
}
