package com.ucfgroup.client.beetle.bean.getnodedataresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class Info   {

	@JsonProperty("id")
	private String id;
	@JsonProperty("name")
	private String name;
	@JsonProperty("system")
	private String system;
	@JsonProperty("company")
	private String company;
	@JsonProperty("subcompany")
	private String subcompany;
	@JsonProperty("dept")
	private String dept;
	@JsonProperty("team")
	private String team;
	@JsonProperty("usera")
	private String usera;
	@JsonProperty("org")
	private String org;
	@JsonProperty("userb")
	private String userb;
	@JsonProperty("level")
	private String level;
	@JsonProperty("upper_id")
	private String upperId;
	@JsonProperty("childs")
	private List<String> childsList;
	@JsonProperty("code")
	private String code;
	@JsonProperty("groupid")
	private String groupid;
	@JsonProperty("row_prefix")
	private String rowPrefix;
	@JsonProperty("short_alias")
	private String shortAlias;
	@JsonProperty("weight")
	private String weight;
	@JsonProperty("remark")
	private String remark;
	@JsonProperty("ctime")
	private String ctime;
	@JsonProperty("mtime")
	private String mtime;
	@JsonProperty("parents")
	private List<Parents> parentsList;
	@JsonProperty("secondids")
	private List<Secondids> secondidsList;
	@JsonProperty("manager")
	private List<String> managerList;
	@JsonProperty("userb_num")
	private String userbNum;
	@JsonProperty("referer_rebate_money")
	private String refererRebateMoney;
	@JsonProperty("invest_money")
	private String investMoney;
	@JsonProperty("invest_year_money")
	private String investYearMoney;
	@JsonProperty("reg_num")
	private String regNum;
	@JsonProperty("invest_count")
	private String investCount;
	@JsonProperty("invest_num")
	private String investNum;
	@JsonProperty("current_invest_num")
	private String currentInvestNum;
	@JsonProperty("firstinvest_num")
	private String firstinvestNum;
	@JsonProperty("is_leaf")
	private String isLeaf;
	@XStreamOmitField
	private boolean converted;

    public Info() {
    }
 	
	public Info convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getSystem(){
     	return system;
     }

     public void setSystem(String system){
     	this.system = system;
     }
	 	 	 
     public String getCompany(){
     	return company;
     }

     public void setCompany(String company){
     	this.company = company;
     }
	 	 	 
     public String getSubcompany(){
     	return subcompany;
     }

     public void setSubcompany(String subcompany){
     	this.subcompany = subcompany;
     }
	 	 	 
     public String getDept(){
     	return dept;
     }

     public void setDept(String dept){
     	this.dept = dept;
     }
	 	 	 
     public String getTeam(){
     	return team;
     }

     public void setTeam(String team){
     	this.team = team;
     }
	 	 	 
     public String getUsera(){
     	return usera;
     }

     public void setUsera(String usera){
     	this.usera = usera;
     }
	 	 	 
     public String getOrg(){
     	return org;
     }

     public void setOrg(String org){
     	this.org = org;
     }
	 	 	 
     public String getUserb(){
     	return userb;
     }

     public void setUserb(String userb){
     	this.userb = userb;
     }
	 	 	 
     public String getLevel(){
     	return level;
     }

     public void setLevel(String level){
     	this.level = level;
     }
	 	 	 
     public String getUpperId(){
     	return upperId;
     }

     public void setUpperId(String upperId){
     	this.upperId = upperId;
     }
	 	 	 
     public List<String> getChildsList(){
     	return childsList;
     }

     public void setChildsList(List<String> childsList){
     	this.childsList = childsList;
     }
	 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }
	 	 	 
     public String getGroupid(){
     	return groupid;
     }

     public void setGroupid(String groupid){
     	this.groupid = groupid;
     }
	 	 	 
     public String getRowPrefix(){
     	return rowPrefix;
     }

     public void setRowPrefix(String rowPrefix){
     	this.rowPrefix = rowPrefix;
     }
	 	 	 
     public String getShortAlias(){
     	return shortAlias;
     }

     public void setShortAlias(String shortAlias){
     	this.shortAlias = shortAlias;
     }
	 	 	 
     public String getWeight(){
     	return weight;
     }

     public void setWeight(String weight){
     	this.weight = weight;
     }
	 	 	 
     public String getRemark(){
     	return remark;
     }

     public void setRemark(String remark){
     	this.remark = remark;
     }
	 	 	 
     public String getCtime(){
     	return ctime;
     }

     public void setCtime(String ctime){
     	this.ctime = ctime;
     }
	 	 	 
     public String getMtime(){
     	return mtime;
     }

     public void setMtime(String mtime){
     	this.mtime = mtime;
     }
	 	 	 
     public List<Parents> getParentsList(){
     	return parentsList;
     }

     public void setParentsList(List<Parents> parentsList){
     	this.parentsList = parentsList;
     }
	 	 	 
     public List<Secondids> getSecondidsList(){
     	return secondidsList;
     }

     public void setSecondidsList(List<Secondids> secondidsList){
     	this.secondidsList = secondidsList;
     }
	 	 	 
     public List<String> getManagerList(){
     	return managerList;
     }

     public void setManagerList(List<String> managerList){
     	this.managerList = managerList;
     }
	 	 	 
     public String getUserbNum(){
     	return userbNum;
     }

     public void setUserbNum(String userbNum){
     	this.userbNum = userbNum;
     }
	 	 	 
     public String getRefererRebateMoney(){
     	return refererRebateMoney;
     }

     public void setRefererRebateMoney(String refererRebateMoney){
     	this.refererRebateMoney = refererRebateMoney;
     }
	 	 	 
     public String getInvestMoney(){
     	return investMoney;
     }

     public void setInvestMoney(String investMoney){
     	this.investMoney = investMoney;
     }
	 	 	 
     public String getInvestYearMoney(){
     	return investYearMoney;
     }

     public void setInvestYearMoney(String investYearMoney){
     	this.investYearMoney = investYearMoney;
     }
	 	 	 
     public String getRegNum(){
     	return regNum;
     }

     public void setRegNum(String regNum){
     	this.regNum = regNum;
     }
	 	 	 
     public String getInvestCount(){
     	return investCount;
     }

     public void setInvestCount(String investCount){
     	this.investCount = investCount;
     }
	 	 	 
     public String getInvestNum(){
     	return investNum;
     }

     public void setInvestNum(String investNum){
     	this.investNum = investNum;
     }
	 	 	 
     public String getCurrentInvestNum(){
     	return currentInvestNum;
     }

     public void setCurrentInvestNum(String currentInvestNum){
     	this.currentInvestNum = currentInvestNum;
     }
	 	 	 
     public String getFirstinvestNum(){
     	return firstinvestNum;
     }

     public void setFirstinvestNum(String firstinvestNum){
     	this.firstinvestNum = firstinvestNum;
     }
	 	 	 
     public String getIsLeaf(){
     	return isLeaf;
     }

     public void setIsLeaf(String isLeaf){
     	this.isLeaf = isLeaf;
     }
	 	 
}
