package com.ucfgroup.client.beetle.bean.getnodedataresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class Invest   {

	@JsonProperty("referer_rebate_money")
	private String refererRebateMoney;
	@JsonProperty("invest_money")
	private String investMoney;
	@JsonProperty("invest_year_money")
	private String investYearMoney;
	@JsonProperty("reg_num")
	private String regNum;
	@JsonProperty("invest_count")
	private String investCount;
	@JsonProperty("invest_num")
	private String investNum;
	@JsonProperty("current_invest_num")
	private String currentInvestNum;
	@JsonProperty("firstinvest_num")
	private String firstinvestNum;
	@JsonProperty("is_leaf")
	private String isLeaf;
	@JsonProperty("ctime")
	private String ctime;
	@XStreamOmitField
	private boolean converted;

    public Invest() {
    }
 	
	public Invest convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getRefererRebateMoney(){
     	return refererRebateMoney;
     }

     public void setRefererRebateMoney(String refererRebateMoney){
     	this.refererRebateMoney = refererRebateMoney;
     }
	 	 	 
     public String getInvestMoney(){
     	return investMoney;
     }

     public void setInvestMoney(String investMoney){
     	this.investMoney = investMoney;
     }
	 	 	 
     public String getInvestYearMoney(){
     	return investYearMoney;
     }

     public void setInvestYearMoney(String investYearMoney){
     	this.investYearMoney = investYearMoney;
     }
	 	 	 
     public String getRegNum(){
     	return regNum;
     }

     public void setRegNum(String regNum){
     	this.regNum = regNum;
     }
	 	 	 
     public String getInvestCount(){
     	return investCount;
     }

     public void setInvestCount(String investCount){
     	this.investCount = investCount;
     }
	 	 	 
     public String getInvestNum(){
     	return investNum;
     }

     public void setInvestNum(String investNum){
     	this.investNum = investNum;
     }
	 	 	 
     public String getCurrentInvestNum(){
     	return currentInvestNum;
     }

     public void setCurrentInvestNum(String currentInvestNum){
     	this.currentInvestNum = currentInvestNum;
     }
	 	 	 
     public String getFirstinvestNum(){
     	return firstinvestNum;
     }

     public void setFirstinvestNum(String firstinvestNum){
     	this.firstinvestNum = firstinvestNum;
     }
	 	 	 
     public String getIsLeaf(){
     	return isLeaf;
     }

     public void setIsLeaf(String isLeaf){
     	this.isLeaf = isLeaf;
     }
	 	 	 
     public String getCtime(){
     	return ctime;
     }

     public void setCtime(String ctime){
     	this.ctime = ctime;
     }
	 	 
}
