package com.ucfgroup.client.beetle.bean.getnodedataresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class Parents   {

	@JsonProperty("id")
	private String id;
	@JsonProperty("level")
	private String level;
	@JsonProperty("name")
	private String name;
	@XStreamOmitField
	private boolean converted;

    public Parents() {
    }
 	
	public Parents convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getLevel(){
     	return level;
     }

     public void setLevel(String level){
     	this.level = level;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 
}
