package com.hframework.strategy.rule.repository;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.hframework.strategy.rule.repository.rules.*;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("rules")
public class Rules   {

	@XStreamImplicit/n    @XStreamAlias("rule")
	private List<Rule> ruleList;

    public Rules() {
    }
   
 	 	 
     public List<Rule> getRuleList(){
     	return ruleList;
     }

     public void setRuleList(List<Rule> ruleList){
     	this.ruleList = ruleList;
     }
	 
}
