package com.ucfgroup.client.ucfpay.bean;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hframework.common.util.message.*;

/**
 * generated by hframework on 2016-04-27.
 */
public class UcfPayCardBinResult   {

	@JsonProperty("bankName")
	private String bankName;
	@JsonProperty("cardType")
	private String cardType;
	@JsonProperty("bankCardNo")
	private String bankCardNo;
	@JsonProperty("bankCode")
	private String bankCode;
	@JsonProperty("status")
	private String status;
	@JsonProperty("respMsg")
	private String respMsg;
	
	private boolean converted;

    public UcfPayCardBinResult() {
    }
 	
	public UcfPayCardBinResult convert()  throws Exception{
			return this;
	}

  
 	 	 
     public String getBankName(){
     	return bankName;
     }

     public void setBankName(String bankName){
     	this.bankName = bankName;
     }
	 	 	 
     public String getCardType(){
     	return cardType;
     }

     public void setCardType(String cardType){
     	this.cardType = cardType;
     }
	 	 	 
     public String getBankCardNo(){
     	return bankCardNo;
     }

     public void setBankCardNo(String bankCardNo){
     	this.bankCardNo = bankCardNo;
     }
	 	 	 
     public String getBankCode(){
     	return bankCode;
     }

     public void setBankCode(String bankCode){
     	this.bankCode = bankCode;
     }
	 	 	 
     public String getStatus(){
     	return status;
     }

     public void setStatus(String status){
     	this.status = status;
     }
	 	 	 
     public String getRespMsg(){
     	return respMsg;
     }

     public void setRespMsg(String respMsg){
     	this.respMsg = respMsg;
     }
	 	 
}
