package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("datanode")
public class Datanode   {

	@XStreamAsAttribute
    @XStreamAlias("leftName")
	private String leftName;
	@XStreamAsAttribute
    @XStreamAlias("rightName")
	private String rightName;
	@XStreamAsAttribute
    @XStreamAlias("isKey")
	private String isKey;

    public Datanode() {
    }
   
 	 	 
     public String getLeftName(){
     	return leftName;
     }

     public void setLeftName(String leftName){
     	this.leftName = leftName;
     }
	 	 	 
     public String getRightName(){
     	return rightName;
     }

     public void setRightName(String rightName){
     	this.rightName = rightName;
     }
	 	 	 
     public String getIsKey(){
     	return isKey;
     }

     public void setIsKey(String isKey){
     	this.isKey = isKey;
     }
	 
}
