package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("exporter")
public class Exporter   {

	@XStreamAlias("sql")
	private String sql;
	@XStreamAlias("leftId")
	private String leftId;
	@XStreamAlias("rightId")
	private String rightId;
	@XStreamAlias("host")
	private Host host;
	@XStreamAlias("file")
	private File file;
	@XStreamAlias("dataitem")
	private String dataitem;
	@XStreamAlias("scope")
	private String scope;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;

    public Exporter() {
    }
   
 	 	 
     public String getSql(){
     	return sql;
     }

     public void setSql(String sql){
     	this.sql = sql;
     }
	 	 	 
     public String getLeftId(){
     	return leftId;
     }

     public void setLeftId(String leftId){
     	this.leftId = leftId;
     }
	 	 	 
     public String getRightId(){
     	return rightId;
     }

     public void setRightId(String rightId){
     	this.rightId = rightId;
     }
	 	 	 
     public Host getHost(){
     	return host;
     }

     public void setHost(Host host){
     	this.host = host;
     }
	 	 	 
     public File getFile(){
     	return file;
     }

     public void setFile(File file){
     	this.file = file;
     }
	 	 	 
     public String getDataitem(){
     	return dataitem;
     }

     public void setDataitem(String dataitem){
     	this.dataitem = dataitem;
     }
	 	 	 
     public String getScope(){
     	return scope;
     }

     public void setScope(String scope){
     	this.scope = scope;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 
}
