package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("exporters")
public class Exporters   {

	@XStreamImplicit
    @XStreamAlias("exporter")
	private List<Exporter> exporterList;

    public Exporters() {
    }
   
 	 	 
     public List<Exporter> getExporterList(){
     	return exporterList;
     }

     public void setExporterList(List<Exporter> exporterList){
     	this.exporterList = exporterList;
     }
	 
}
