package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("file")
public class File   {

	@XStreamImplicit
    @XStreamAlias("row")
	private List<Row> rowList;
	@XStreamAsAttribute
    @XStreamAlias("path")
	private String path;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;
	@XStreamAsAttribute
    @XStreamAlias("tmpPath")
	private String tmpPath;
	@XStreamAsAttribute
    @XStreamAlias("parser")
	private String parser;

    public File() {
    }
   
 	 	 
     public List<Row> getRowList(){
     	return rowList;
     }

     public void setRowList(List<Row> rowList){
     	this.rowList = rowList;
     }
	 	 	 
     public String getPath(){
     	return path;
     }

     public void setPath(String path){
     	this.path = path;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getTmpPath(){
     	return tmpPath;
     }

     public void setTmpPath(String tmpPath){
     	this.tmpPath = tmpPath;
     }
	 	 	 
     public String getParser(){
     	return parser;
     }

     public void setParser(String parser){
     	this.parser = parser;
     }
	 
}
