package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("host")
public class Host   {

	@XStreamAlias("datasource")
	private Datasource datasource;
	@XStreamAlias("username")
	private String username;
	@XStreamAlias("password")
	private String password;
	@XStreamAlias("cxtpath")
	private String cxtpath;
	@XStreamAsAttribute
    @XStreamAlias("rel")
	private String rel;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;

    public Host() {
    }
   
 	 	 
     public Datasource getDatasource(){
     	return datasource;
     }

     public void setDatasource(Datasource datasource){
     	this.datasource = datasource;
     }
	 	 	 
     public String getUsername(){
     	return username;
     }

     public void setUsername(String username){
     	this.username = username;
     }
	 	 	 
     public String getPassword(){
     	return password;
     }

     public void setPassword(String password){
     	this.password = password;
     }
	 	 	 
     public String getCxtpath(){
     	return cxtpath;
     }

     public void setCxtpath(String cxtpath){
     	this.cxtpath = cxtpath;
     }
	 	 	 
     public String getRel(){
     	return rel;
     }

     public void setRel(String rel){
     	this.rel = rel;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 
}
