package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("row")
public class Row   {

	@XStreamImplicit
    @XStreamAlias("item")
	private List<Item> itemList;
	@XStreamAsAttribute
    @XStreamAlias("separator")
	private String separator;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("rowspan")
	private String rowspan;
	@XStreamAsAttribute
    @XStreamAlias("express")
	private String express;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;

    public Row() {
    }
   
 	 	 
     public List<Item> getItemList(){
     	return itemList;
     }

     public void setItemList(List<Item> itemList){
     	this.itemList = itemList;
     }
	 	 	 
     public String getSeparator(){
     	return separator;
     }

     public void setSeparator(String separator){
     	this.separator = separator;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getRowspan(){
     	return rowspan;
     }

     public void setRowspan(String rowspan){
     	this.rowspan = rowspan;
     }
	 	 	 
     public String getExpress(){
     	return express;
     }

     public void setExpress(String express){
     	this.express = express;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 
}
