package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("rule")
public class Rule   {

	@XStreamImplicit
    @XStreamAlias("datanode")
	private List<Datanode> datanodeList;
	@XStreamAsAttribute
    @XStreamAlias("leftId")
	private String leftId;
	@XStreamAsAttribute
    @XStreamAlias("rightId")
	private String rightId;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;

    public Rule() {
    }
   
 	 	 
     public List<Datanode> getDatanodeList(){
     	return datanodeList;
     }

     public void setDatanodeList(List<Datanode> datanodeList){
     	this.datanodeList = datanodeList;
     }
	 	 	 
     public String getLeftId(){
     	return leftId;
     }

     public void setLeftId(String leftId){
     	this.leftId = leftId;
     }
	 	 	 
     public String getRightId(){
     	return rightId;
     }

     public void setRightId(String rightId){
     	this.rightId = rightId;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 
}
