package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("ruleCenter")
public class RuleCenter   {

	@XStreamImplicit
    @XStreamAlias("rule")
	private List<Rule> ruleList;

    public RuleCenter() {
    }
   
 	 	 
     public List<Rule> getRuleList(){
     	return ruleList;
     }

     public void setRuleList(List<Rule> ruleList){
     	this.ruleList = ruleList;
     }
	 
}
