package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("services")
public class Services   {

	@XStreamImplicit
    @XStreamAlias("service")
	private List<Service> serviceList;

    public Services() {
    }
   
 	 	 
     public List<Service> getServiceList(){
     	return serviceList;
     }

     public void setServiceList(List<Service> serviceList){
     	this.serviceList = serviceList;
     }
	 
}
