package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("sql")
@XStreamConverter(value=ToAttributedValueConverter.class, strings={"text"})
public class Sql   {

	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	
	private String text;

    public Sql() {
    }
   
 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getText(){
     	return text;
     }

     public void setText(String text){
     	this.text = text;
     }
	 
}
