package com.hframework.reconciliation.bean.config;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("trigger")
@XStreamConverter(value=ToAttributedValueConverter.class, strings={"text"})
public class Trigger   {

	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	
	private String text;

    public Trigger() {
    }
   
 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getText(){
     	return text;
     }

     public void setText(String text){
     	this.text = text;
     }
	 
}
