package com.ucfgroup.client.beetle.bean.getregdetailresponse;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hframework.common.util.message.XmlUtils;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * generated by hframework on 2016-04-22.
 */
public class Data   {

	@JsonProperty("id")
	private String id;
	@JsonProperty("consume_user_name")
	private String consumeUserName;
	@JsonProperty("consume_real_name")
	private String consumeRealName;
	@JsonProperty("mobile")
	private String mobile;
	@JsonProperty("group_id")
	private String groupId;
	@JsonProperty("refer_short_alias")
	private String referShortAlias;
	@JsonProperty("refer_user_id")
	private String referUserId;
	@JsonProperty("create_time")
	private String createTime;
	@JsonProperty("user_status")
	private String userStatus;
	@JsonProperty("refer_real_name")
	private String referRealName;
	@XStreamOmitField
	private boolean converted;

    public Data() {
    }
 	
	public Data convert()  throws Exception{
			if(!converted) {
			   String beforeInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(beforeInfo);
			   converted = true;
			   String afterInfo = XmlUtils.writeValueAsString(this);
			   System.out.println(afterInfo);
			}
			return this;
	}

  
 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getConsumeUserName(){
     	return consumeUserName;
     }

     public void setConsumeUserName(String consumeUserName){
     	this.consumeUserName = consumeUserName;
     }
	 	 	 
     public String getConsumeRealName(){
     	return consumeRealName;
     }

     public void setConsumeRealName(String consumeRealName){
     	this.consumeRealName = consumeRealName;
     }
	 	 	 
     public String getMobile(){
     	return mobile;
     }

     public void setMobile(String mobile){
     	this.mobile = mobile;
     }
	 	 	 
     public String getGroupId(){
     	return groupId;
     }

     public void setGroupId(String groupId){
     	this.groupId = groupId;
     }
	 	 	 
     public String getReferShortAlias(){
     	return referShortAlias;
     }

     public void setReferShortAlias(String referShortAlias){
     	this.referShortAlias = referShortAlias;
     }
	 	 	 
     public String getReferUserId(){
     	return referUserId;
     }

     public void setReferUserId(String referUserId){
     	this.referUserId = referUserId;
     }
	 	 	 
     public String getCreateTime(){
     	return createTime;
     }

     public void setCreateTime(String createTime){
     	this.createTime = createTime;
     }
	 	 	 
     public String getUserStatus(){
     	return userStatus;
     }

     public void setUserStatus(String userStatus){
     	this.userStatus = userStatus;
     }
	 	 	 
     public String getReferRealName(){
     	return referRealName;
     }

     public void setReferRealName(String referRealName){
     	this.referRealName = referRealName;
     }
	 	 
}
