package com.ucfgroup.client.beetle;

import com.hframework.common.util.message.JsonUtils;
import org.junit.Test;
import com.ucfgroup.client.beetle.bean.*;

/**
 * generated by hframework on 2016-04-22.
 */
public class BeetleClientTest   {

	@Test
	public void getNodeInfo()  throws Exception{
			GetNodeInfoResponse result =BeetleClient.getNodeInfo("1500123");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getNodeData()  throws Exception{
			GetNodeDataResponse result =BeetleClient.getNodeData("1500123","day",0);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getRegDetail()  throws Exception{
			GetRegDetailResponse result =BeetleClient.getRegDetail("1500123","month",0);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getFirstinvestDetail()  throws Exception{
			GetFirstinvestDetailResponse result =BeetleClient.getFirstinvestDetail("1500123","month",0);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getRepayPlan()  throws Exception{
			GetRepayPlanResponse result =BeetleClient.getRepayPlan(1,0,0,20);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getAssetChange()  throws Exception{
			GetAssetChangeResponse result =BeetleClient.getAssetChange(12,"",1,20);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

	@Test
	public void getAdList()  throws Exception{
			GetAdListResponse result =BeetleClient.getAdList("all",3);
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

  
 
}
